package guru.sfg.beer.order.service.domain;

public enum BeerOrderEven {
    VALIDATE_ORDER, VALIDATION_PASS, VALIDATION_FAIL, ALLOCATION_SUCCESS, ALLOCATION_NO_INVENTORY, ALLOCATION_FAILED, BEER_ORDER_PICKED_UP
}
